version: "3"

services:
  playsms:
    image: zhironghuang/playsms-gammu:latest
    restart: unless-stopped
    devices:
      - "/dev/ttyUSB1:/dev/ttyUSB0"
    container_name: PlaySMS
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 9080:80
    environment:
      - DBUSER=playsms
      - DBPASS=playsmspwdfordb
      - DBNAME=playsms
      - DBHOST=192.168.1.250
      - DBPORT=3306
